import eslintConfigPrettier from "eslint-config-prettier";
import functional from "eslint-plugin-functional";
import imprt from "eslint-plugin-import";
import pluginN from "eslint-plugin-n";
import pluginPromise from "eslint-plugin-promise";

export default [
  eslintConfigPrettier,
  {
    files: ["**/*.{ts,js}"],
    plugins: {
      functional,
      n: pluginN,
      import: imprt,
      promise: pluginPromise,
    },
    languageOptions: {
      ecmaVersion: "latest",
      parserOptions: {
        ecmaFeatures: { modules: true, jsx: true },
        ecmaVersion: "latest",
      },
      globals: {
        ...{
          __dirname: false,
          __filename: false,
          AbortController: false,
          AbortSignal: false,
          atob: false,
          Blob: false,
          BroadcastChannel: false,
          btoa: false,
          Buffer: false,
          ByteLengthQueuingStrategy: false,
          clearImmediate: false,
          clearInterval: false,
          clearTimeout: false,
          CompressionStream: false,
          console: false,
          CountQueuingStrategy: false,
          crypto: false,
          Crypto: false,
          CryptoKey: false,
          CustomEvent: false,
          DecompressionStream: false,
          DOMException: false,
          Event: false,
          EventTarget: false,
          exports: true,
          fetch: false,
          File: false,
          FormData: false,
          global: false,
          Headers: false,
          Iterator: false,
          MessageChannel: false,
          MessageEvent: false,
          MessagePort: false,
          module: false,
          navigator: false,
          Navigator: false,
          performance: false,
          Performance: false,
          PerformanceEntry: false,
          PerformanceMark: false,
          PerformanceMeasure: false,
          PerformanceObserver: false,
          PerformanceObserverEntryList: false,
          PerformanceResourceTiming: false,
          process: false,
          queueMicrotask: false,
          ReadableByteStreamController: false,
          ReadableStream: false,
          ReadableStreamBYOBReader: false,
          ReadableStreamBYOBRequest: false,
          ReadableStreamDefaultController: false,
          ReadableStreamDefaultReader: false,
          Request: false,
          require: false,
          Response: false,
          setImmediate: false,
          setInterval: false,
          setTimeout: false,
          structuredClone: false,
          SubtleCrypto: false,
          TextDecoder: false,
          TextDecoderStream: false,
          TextEncoder: false,
          TextEncoderStream: false,
          TransformStream: false,
          TransformStreamDefaultController: false,
          URL: false,
          URLSearchParams: false,
          WebAssembly: false,
          WebSocket: false,
          WritableStream: false,
          WritableStreamDefaultController: false,
          WritableStreamDefaultWriter: false,
        },
        ...{
          AggregateError: false,
          Array: false,
          ArrayBuffer: false,
          Atomics: false,
          BigInt: false,
          BigInt64Array: false,
          BigUint64Array: false,
          Boolean: false,
          DataView: false,
          Date: false,
          decodeURI: false,
          decodeURIComponent: false,
          encodeURI: false,
          encodeURIComponent: false,
          Error: false,
          escape: false,
          eval: false,
          EvalError: false,
          FinalizationRegistry: false,
          Float32Array: false,
          Float64Array: false,
          Function: false,
          globalThis: false,
          Infinity: false,
          Int16Array: false,
          Int32Array: false,
          Int8Array: false,
          Intl: false,
          isFinite: false,
          isNaN: false,
          JSON: false,
          Map: false,
          Math: false,
          NaN: false,
          Number: false,
          Object: false,
          parseFloat: false,
          parseInt: false,
          Promise: false,
          Proxy: false,
          RangeError: false,
          ReferenceError: false,
          Reflect: false,
          RegExp: false,
          Set: false,
          SharedArrayBuffer: false,
          String: false,
          Symbol: false,
          SyntaxError: false,
          TypeError: false,
          Uint16Array: false,
          Uint32Array: false,
          Uint8Array: false,
          Uint8ClampedArray: false,
          undefined: false,
          unescape: false,
          URIError: false,
          WeakMap: false,
          WeakRef: false,
          WeakSet: false,
        },
      },
    },
    rules: {
      "eol-last": "error",
      "quotes": "off",
      "semi": "off",
      "no-constant-binary-expression": "warn",
      "no-var": "warn",
      "no-new": "error",
      "no-eval": "error",
      "no-void": "error",
      "no-tabs": "error",
      "no-with": "error",
      "no-undef": "error",
      "no-octal": "error",
      "no-proto": "error",
      "no-caller": "error",
      "no-console": "off",
      "no-iterator": "error",
      "no-debugger": "warn",
      "no-new-func": "error",
      "quote-props": ["error", "consistent"],
      "no-dupe-keys": "error",
      "no-obj-calls": "error",
      "no-new-object": "error",
      "no-multi-str": "error",
      "no-sequences": "error",
      "no-ex-assign": "error",
      "no-dupe-args": "error",
      "no-sequences": "warn",
      "no-delete-var": "error",
      "no-undef-init": "error",
      "no-extra-bind": "error",
      "no-new-symbol": "error",
      "no-fallthrough": "error",
      "no-unreachable": "error",
      "no-func-assign": "error",
      "no-cond-assign": "error",
      "no-const-assign": "error",
      "no-implied-eval": "error",
      "no-octal-escape": "error",
      "no-class-assign": "error",
      "no-new-wrappers": "error",
      "no-useless-call": "error",
      "no-multi-spaces": "error",
      "no-self-compare": "error",
      "space-infix-ops": "error",
      "no-regex-spaces": "error",
      "no-import-assign": "error",
      "no-global-assign": "error",
      "no-sparse-arrays": "error",
      "no-throw-literal": "error",
      "no-control-regex": "error",
      "no-useless-catch": "error",
      "no-extend-native": "error",
      "no-empty-pattern": "error",
      "no-import-assign": "warn",
      "no-extend-native": "warn",
      "no-unsafe-finally": "error",
      "no-invalid-regexp": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-duplicate-case": "error",
      "symbol-description": "error",
      "no-trailing-spaces": "error",
      "no-unsafe-negation": "error",
      "no-compare-neg-zero": "error",
      "no-unreachable-loop": "error",
      "no-case-declarations": "warn",
      "no-array-constructor": "error",
      "no-this-before-super": "error",
      "no-loss-of-precision": "error",
      "no-prototype-builtins": "error",
      "no-extra-boolean-cast": "error",
      "no-dupe-class-members": "error",
      "no-prototype-builtins": "warn",
      "no-unused-expressions": "warn",
      "no-useless-constructor": "error",
      "no-unexpected-multiline": "error",
      "no-irregular-whitespace": "error",
      "no-useless-computed-key": "error",
      "no-irregular-whitespace": "error",
      "no-useless-backreference": "error",
      "no-mixed-spaces-and-tabs": "error",
      "no-async-promise-executor": "off",
      "no-empty-character-class": "error",
      "no-shadow-restricted-names": "error",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "error",
      "prefer-promise-reject-errors": "error",
      "no-misleading-character-class": "error",
      "no-whitespace-before-property": "error",
      "yoda": ["error", "never"],
      "unicode-bom": ["error", "never"],
      "space-in-parens": ["error", "never"],
      "yield-star-spacing": ["error", "both"],
      "no-extra-parens": ["error", "functions"],
      "rest-spread-spacing": ["error", "never"],
      "space-before-blocks": ["error", "always"],
      "template-tag-spacing": ["error", "never"],
      "object-curly-spacing": ["error", "always"],
      "template-curly-spacing": ["error", "never"],
      "space-before-function-paren": ["error", "always"],
      "no-return-assign": ["error", "except-parens"],
      "no-self-assign": ["error", { props: true }],
      "one-var": ["error", { initialized: "never" }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "prefer-const": ["error", { destructuring: "all" }],
      "no-redeclare": ["error", { builtinGlobals: false }],
      "semi-spacing": ["error", { before: false, after: true }],
      "no-constant-condition": ["error", { checkLoops: false }],
      "valid-typeof": ["error", { requireStringLiterals: true }],
      "space-unary-ops": ["error", { words: true, nonwords: false }],
      "no-unneeded-ternary": ["error", { defaultAssignment: false }],
      "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
      "wrap-iife": ["error", "any", { functionPrototypeMethods: true }],
      "no-multiple-empty-lines": ["error", { max: 1, maxBOF: 0, maxEOF: 0 }],
      "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
      "object-curly-newline": ["error", { multiline: true, consistent: true }],
      "object-property-newline": ["error", { allowMultiplePropertiesPerLine: true }],
      "padded-blocks": ["error", { blocks: "never", switches: "never", classes: "never" }],
      "no-use-before-define": ["error", { functions: false, classes: false, variables: false }],
      "use-isnan": [
        "error",
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      "operator-linebreak": [
        "error",
        "after",
        { overrides: { "?": "before", ":": "before", "|>": "before" } },
      ],
      "spaced-comment": [
        "error",
        "always",
        {
          line: { markers: ["*package", "!", "/", ",", "="] },
          block: {
            balanced: true,
            markers: ["*package", "!", ",", ":", "::", "flow-include"],
            exceptions: ["*"],
          },
        },
      ],
      "no-unused-expressions": [
        "error",
        {
          allowShortCircuit: true,
          allowTernary: true,
          allowTaggedTemplates: true,
        },
      ],
      "no-unused-vars": [
        "error",
        {
          args: "none",
          caughtErrors: "none",
          ignoreRestSiblings: true,
          vars: "all",
        },
      ],
      "no-mixed-operators": [
        "error",
        {
          groups: [
            ["==", "!=", "===", "!==", ">", ">=", "<", "<="],
            ["&&", "||"],
            ["in", "instanceof"],
          ],
          allowSamePrecedence: true,
        },
      ],
      "no-floating-decimal": "error",
      "no-lone-blocks": "error",
      "space-before-function-paren": "off",
      "no-unused-vars": "warn",
      "object-shorthand": ["warn", "properties"],
      "object-curly-newline": [
        "warn",
        {
          consistent: true,
          multiline: true,
        },
      ],
      "object-curly-spacing": ["warn", "always"],
      "array-element-newline": ["warn", "consistent"],
      "array-bracket-newline": ["warn", "consistent"],
      "accessor-pairs": ["error", { setWithoutGet: true, enforceForClassMembers: true }],
      "arrow-spacing": ["error", { before: true, after: true }],
      "array-bracket-spacing": ["error", "never"],
      "array-callback-return": [
        "error",
        {
          allowImplicit: false,
          checkForEach: false,
        },
      ],
      "block-spacing": ["error", "always"],
      "brace-style": ["error", "1tbs", { allowSingleLine: true }],
      "camelcase": [
        "error",
        {
          allow: ["^UNSAFE_"],
          properties: "never",
          ignoreGlobals: true,
        },
      ],
      "comma-spacing": ["error", { before: false, after: true }],
      "comma-style": ["error", "last"],
      "computed-property-spacing": ["error", "never", { enforceForClassMembers: true }],
      "constructor-super": "error",
      "curly": ["error", "multi-line"],
      "default-case-last": "error",
      "dot-location": ["error", "property"],
      "dot-notation": ["error", { allowKeywords: true }],
      "eqeqeq": ["error", "always", { null: "ignore" }],
      "func-call-spacing": ["error", "never"],
      "generator-star-spacing": ["error", { before: true, after: true }],
      "key-spacing": ["error", { beforeColon: false, afterColon: true }],
      "keyword-spacing": ["error", { before: true, after: true }],
      "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
      "multiline-ternary": ["error", "always-multiline"],
      "new-cap": ["error", { newIsCap: true, capIsNew: false, properties: true }],
      "new-parens": "error",
      "import/export": "error",
      "import/first": "error",
      "import/no-absolute-path": ["error", { esmodule: true, commonjs: true, amd: false }],
      "import/no-duplicates": "error",
      "import/no-named-default": "error",
      "import/no-webpack-loader-syntax": "error",
      "n/handle-callback-err": ["error", "^(err|error)$"],
      "n/no-callback-literal": "error",
      "n/no-deprecated-api": "error",
      "n/no-exports-assign": "error",
      "n/no-new-require": "error",
      "n/no-path-concat": "error",
      "n/process-exit-as-throw": "error",
      "promise/param-names": "error",
    },
  },
];
